USE default;
DROP TABLE IF EXISTS test_load_data010;
CREATE TABLE IF NOT EXISTS test_load_data010 (
    id INT,
    name STRING
)
PARTITIONED BY (dt STRING, device STRING, type_id INT)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

DROP TABLE IF EXISTS test_load_data015;
CREATE TABLE IF NOT EXISTS test_load_data015 (
    id INT,
    name STRING
)
PARTITIONED BY (dt STRING, device STRING, type_id INT)
STORED AS SEQUENCEFILE;
